include: package:very_good_analysis/analysis_options.yaml

analyzer:
  plugins:
    - custom_lint
  errors:
    invalid_annotation_target: ignore
  exclude:
    - "**.g.dart"
    - "**.mocks.dart"
    - lib/generated/*

linter:
  rules:
    sort_pub_dependencies: false
    public_member_api_docs: false
    avoid_positional_boolean_parameters: false
